### ISSUE TITLE
Forgotten intercept in SGDRegressor

### ISSUE THREAD

**Issue by StrikerRUS** [scikit-learn-contrib/lightning#141]
Hey guys!

Seems that there is a bug in the `predict` method of `SGDRegressor`.

Shouldn't `intercept_` be added here?

https://github.com/scikit-learn-contrib/lightning/blob/b96f9c674968496e854078163c8814049a7b9f43/lightning/impl/sgd.py#L395-L406
cf.
https://github.com/scikit-learn-contrib/lightning/blob/b96f9c674968496e854078163c8814049a7b9f43/lightning/impl/base.py#L107-L111

**Comment by StrikerRUS** [comment]
Gently ping @mblondel @MechCoder @zermelozf @fabianp

**Comment by mblondel** [comment]
Yep, I think you're right. Thanks for the catch.
