### ISSUE TITLE
build pb on python 3.9

### ISSUE THREAD

**Issue by agramfort** [scikit-learn-contrib/lightning#153]
we started to have build failures on python 3.9 in benchopt:

https://github.com/benchopt/benchmark_lasso/pull/18/checks?check_run_id=2128864808

thanks for taking a lot.

**Comment by StrikerRUS** [comment]
Hello @agramfort !
You can use the following workaround while the [hot-fix PR](https://github.com/scikit-learn-contrib/lightning/pull/154) is not merged:

https://github.com/BayesWitnesses/m2cgen/blob/6a7d67ff55f7a916981ab0d767f97eec404dfa58/requirements-test.txt#L6
https://github.com/benchopt/benchmark_lasso/blob/ca6f732f7ca370d27170145b971a77d64ef175e7/solvers/lightning.py#L16
