### ISSUE TITLE
Change assert imports

### ISSUE THREAD

**Issue by mblondel** [scikit-learn-contrib/lightning#156]
lightning was relying on `sklearn.utils.testing` to import the `assert_*` functions but they got removed from sklearn. We should import them from `numpy.testing` for the `assert_array_*` and `nose.tools` for the others. @StrikerRUS do you want to tackle this?

**Comment by mblondel** [comment]
We could import all the assertion functions in `impl/tests/utils.py`. This way we can do `from lightning.impl.tests.utils import assert_array_equal` etc (I never remember which assertions are defined numpy.testing and which assertions are defined in nose.tools)

**Comment by StrikerRUS** [comment]
OK, I can take this.
