### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by fabianp** [scikit-learn-contrib/lightning#52]
Hi @mblondel . Some of the recent additions (such as SAGA) don't show up in the webpage. Would you mind pushing a new version of the doc? (I wouldn't mind doing it myself if it was on github pages)

**Comment by mblondel** [comment]
Sure I will do it.

**Comment by fabianp** [comment]
Thanks. I am extensively using lightning with some industrial partners and one of the complications we faced was building on Windows. We solved the problem and I managed to do some conda packages (https://anaconda.org/fabianp/lightning). All is fine but it will be difficult to track versions since lightning has always been on v0.1-git. It would help if we start releasing versions from time to time. I am willing to help as much as I can with this. What do you think?

**Comment by mblondel** [comment]
With your increased involvement in lightning, it would be nice to move the project to a github organization. We can also move the webpage to github. Regarding releases, I had been avoiding them but if you're willing to do them... :)

Regarding the organization, @vene and I had been discussing the idea of a "scikit-learn-contrib" or "scikit-learn-universe" organization where to put various scikit-learn compatible projects. lightning could possibly be moved there. Or we can create our own organization too.

**Comment by fabianp** [comment]
yes to all! As for my involvement, yes, I plan to heavily rely on lightning within the next months, so at least for the close future I will volunteer to maintain it.

I really think releases would positively impact the package quality. However, one problem I foresee is that the pypi page is taken (https://pypi.python.org/pypi/Lightning) :-(

**Comment by vene** [comment]
Very cool, I will try my best to help!

**Comment by mblondel** [comment]
I tried to rebuild the docs but the class references don't display properly. I suspect a bug in sphinx-bootstrap-theme, which lightning currently depends on.

https://pypi.python.org/pypi/sphinx-bootstrap-theme/

I guess it's better to work on scikit-learn-contrib's documentation template then use it for lightning.

**Comment by fabianp** [comment]
I proposed a fix in PR #56 . The references seem to work fine for me with this patch.

**Comment by mblondel** [comment]
Great, thanks! Feel free to create the scikit-learn-contrib.github.io repo and move the documentation in the lightning/ folder.

**Comment by fabianp** [comment]
Done! http://scikit-learn-contrib.github.io/lightning/ :-)

**Comment by mblondel** [comment]
@ogrisel Could you take care of pointing contrib.scikit-learn.org to github? Thanks in advance!

**Comment by mblondel** [comment]
@GaelVaroquaux @ogrisel Do you have the privileges to point contrib.scikit-learn.org to github's servers or should I ask Stéfan van der Walt?

**Comment by ogrisel** [comment]
I think I can do that, let me check.

**Comment by ogrisel** [comment]
This PR needs to be merged https://github.com/scikit-learn-contrib/scikit-learn-contrib.github.io/pull/1

**Comment by mblondel** [comment]
@ogrisel Merged. 

By the way, your invitation to scikit-learn-contrib still appears as pending. Did you receive the email? If not I will send it to you again.

**Comment by ogrisel** [comment]
Joined. The CNAME is in place: http://contrib.scikit-learn.org/lightning/

but there is no top level index: http://contrib.scikit-learn.org/

**Comment by mblondel** [comment]
Works on my side too. Thanks a lot!

**Comment by mblondel** [comment]
I added a temporary index.html.

@fabianp Please update your blog with lightning's new fancy URL :)

**Comment by fabianp** [comment]
cool, done!
