### ISSUE TITLE
0.1 release

### ISSUE THREAD

**Issue by fabianp** [scikit-learn-contrib/lightning#61]
I'd like to do a 0.1 release and upload binary packages to pypi and conda. TODO:

   - [x] Make binary conda packages for (at least) windows (appveyor).
   - [x] Update README with build instructions for binary packages.
   - [x] Update the website with the latests stable version.
   - [x] Create maintenance branch 0.1.X
   - [x] After release, upgrade version number to 0.2.dev0.

What do you think @mblondel ?

**Comment by mblondel** [comment]
+1

Thanks for tackling and this!

**Comment by fabianp** [comment]
I created the maintenance branch 0.1.X and bumped the version number on master to 0.2.dev0

**Comment by fabianp** [comment]
My intention is to only incorporate bug fixes into 0.1.X and make a release next week.

**Comment by fabianp** [comment]
The pypi website is up: https://pypi.python.org/pypi/sklearn-contrib-lightning and there are conda packages for most systems: https://anaconda.org/scikit-learn-contrib/lightning/files

Lets test them a bit and make the announcement within the next days.

**Comment by fabianp** [comment]
(appveyor is slowly uploading the windows packages)

**Comment by mblondel** [comment]
> Lets test them a bit and make the announcement within the next days.

Great! I guess we can announce it on the scikit-learn mailing-list and on Twitter.

**Comment by fabianp** [comment]
It all looks good to me. I'll let you do the announcement whenever you feel its ready.

**Comment by vene** [comment]
Just chiming in to confirm I successfully installed from conda on ubuntu
over here, and all tests pass.

**Comment by fabianp** [comment]
Thanks Vlad!

**Comment by vene** [comment]
Also confirmed on Windows 10 with conda and python3.5. It literally took me
5 minutes to set it up from scratch, the future is truly now :)

Thanks a lot for your work on this, Fabian!!

**Comment by mblondel** [comment]
@fabianp I think you really be the one doing the announcement, since you did all the job.

**Comment by mblondel** [comment]
@fabianp When you get time, could you document in project-template the steps you went through for the release? This would be useful to the @scikit-learn-contrib/py-earth guys.

Also I wonder how much we can automate the process. The dream would be to have a script in project-template that does everything for us :)
