### ISSUE TITLE
Should the .pxd files be included with the distribution?

### ISSUE THREAD

**Issue by vene** [scikit-learn-contrib/lightning#90]
I'm working on a package that uses lightning cython code as a dependency via:

`from lightning.impl.dataset_fast cimport ColumnDataset`.

When installing lightning via conda or pip, generating the cython file fails, but if I distribute the generated cpp files the code runs fine.

Should the .pxd files be distributed with lightning to allow this use case?

**Comment by fabianp** [comment]
Yes the pxd should be installed. I do install them eg for prox_fast.pxd
(see lightning/impl/setup.py). Can you submit a pull request fixing this?

**Comment by vene** [comment]
Well, apparently `'dataset_fast.pxd'` is listed in the setup.py. Still, no .pxd files are included in the package that gets installed either via `pip install sklearn-contrib-lightning` nor via conda, from what I can tell.

Weird, because it's done the exact same way in scipy.linalg, but those pxd files get installed. But scipy also does [this](https://github.com/scipy/scipy/blob/master/scipy/linalg.pxd) one level higher.

scikit-learn doesn't include any pxds at all in the binary distributions, but they are included in the source distribution via MANIFEST.in.

**Comment by fabianp** [comment]
OK then I suppose we should include them also in the MANIFEST.in, right?. Can you submit a PR for this? thanks!

**Comment by vene** [comment]
That might be it, but I don't know whether MANIFEST.in only affects the sdist. Is there a way to test the generated distribution, as it would get released on pypi, so I know that my fix works? I guess I would have to reproduce the steps for a release?

**Comment by vene** [comment]
(is it enough to run `python setup.py sdist` and examine the result?)

**Comment by fabianp** [comment]
the one that gets uploaded to pypi is the one generated by sdist. So if it works for that i think we are safe.

**Comment by fabianp** [comment]
(or at least safer:-)
i can also backport that fix to stable and make a release to double-check

**Comment by fabianp** [comment]
note that you can also pip-install a source file (giving it a local path)

**Comment by kmike** [comment]
Is it fixed by https://github.com/scikit-learn-contrib/lightning/pull/91?

**Comment by vene** [comment]
everything works fine for me with the current releases
